### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MichaelNoseworthy** [MikeTheNose/Assignment-2--Weapon-Shop#6]
Create a file that lists the designer's names, ID's and any information necessary for the project.

**Comment by Maddie273** [comment]
[Data Structures A2 - Documentation.docx](https://github.com/MikeTheNose/Assignment-2--Weapon-Shop/files/1607008/Data.Structures.A2.-.Documentation.docx)

Add your guys Student ID and anything else you can think of

**Comment by MichaelNoseworthy** [comment]
Included my bit.  Just need Kevin @ken-kun to add his ID to the file in the master branch.
